
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author user
 */
public class Card extends javax.swing.JPanel {

    private final int id;
    private final dbConnection db;
    private final String nama;
    private final String agency;
    private final String dateDebut;
    private final String desc;
    private final String photo;            
    private final boolean Talent;


    /**
     * Creates new form Card
     */
    public Card(int id, String nama, String agency, String dateDebut, String desc, String photo, boolean Talent) {
        initComponents();
        db = new dbConnection();
        this.id = id;
        this.nama = nama;
        this.agency = agency;
        this.dateDebut = dateDebut;
        this.desc = desc;
        this.photo = photo;
        this.Talent = Talent;

        labelNama.setText(nama);
        labelAgency.setText(agency);
        labelDebut.setText(dateDebut);
        DescArea.setText(desc);
        Picture.setIcon(new ImageIcon(photo));
        
        if(photo != null){
            ImageIcon pict = new ImageIcon(photo);
            Image img = pict.getImage().getScaledInstance(119, 163, Image.SCALE_SMOOTH);
            Picture.setIcon(new ImageIcon(img));
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pict = new javax.swing.JPanel();
        Picture = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelAgency = new javax.swing.JLabel();
        labelDebut = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescArea = new javax.swing.JTextArea();
        EditButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        Picture.setLabelFor(Picture);
        Picture.setText("Picture");
        Picture.setMaximumSize(new java.awt.Dimension(5161, 2880));
        Picture.setMinimumSize(new java.awt.Dimension(5161, 2880));
        Picture.setPreferredSize(new java.awt.Dimension(5161, 2880));

        javax.swing.GroupLayout PictLayout = new javax.swing.GroupLayout(Pict);
        Pict.setLayout(PictLayout);
        PictLayout.setHorizontalGroup(
            PictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PictLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );
        PictLayout.setVerticalGroup(
            PictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PictLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelNama.setForeground(new java.awt.Color(51, 51, 51));
        labelNama.setText("Name");

        labelAgency.setForeground(new java.awt.Color(51, 51, 51));
        labelAgency.setText("Agency Affiliation");

        labelDebut.setForeground(new java.awt.Color(51, 51, 51));
        labelDebut.setText("Date of Debut");

        DescArea.setEditable(false);
        DescArea.setBackground(new java.awt.Color(204, 204, 204));
        DescArea.setColumns(20);
        DescArea.setForeground(new java.awt.Color(51, 51, 51));
        DescArea.setLineWrap(true);
        DescArea.setRows(5);
        DescArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(DescArea);

        EditButton.setText("Edit");
        EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditButtonMouseClicked(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Name");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Affiliation");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Debut on");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Pict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(EditButton)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNama)
                                    .addComponent(labelAgency)
                                    .addComponent(labelDebut)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Pict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(labelAgency))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDebut)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeleteButton)
                    .addComponent(EditButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        if(this.Talent){
            int input = JOptionPane.showConfirmDialog(null, 
                "Are you sure to Delete this?", "Keep In Mind",JOptionPane.YES_NO_OPTION);
            if(input == 0){
                String sql = "DELETE FROM talent WHERE talent.id_talent='" + this.id + "'";
                db.updateQuery(sql);
            }
            
        }else{
            int input = JOptionPane.showConfirmDialog(null, 
                "Are you sure to Delete this?", "Keep In Mind",JOptionPane.YES_NO_OPTION);
            if(input == 0){
                String sql = "DELETE FROM agency WHERE agency.id_agent='" + this.id + "'";
                db.updateQuery(sql);
            }
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseClicked
        // TODO add your handling code here:
        if(this.Talent){
            EditTalent editpage = new EditTalent(id, nama, agency, dateDebut, desc, photo);
            editpage.setVisible(true);
        }else{
            EditAgency editpageA = new EditAgency(id, nama, agency, dateDebut, desc, photo);
            editpageA.setVisible(true);
        }
        
    }//GEN-LAST:event_EditButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextArea DescArea;
    private javax.swing.JButton EditButton;
    private javax.swing.JPanel Pict;
    private javax.swing.JLabel Picture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAgency;
    private javax.swing.JLabel labelDebut;
    private javax.swing.JLabel labelNama;
    // End of variables declaration//GEN-END:variables
}
